# Generated by Django 4.0.1 on 2022-04-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='write',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='comment',
            name='write',
            field=models.TextField(default='null'),
        ),
    ]
