# Generated by Django 4.0.1 on 2022-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_articles_write_comment_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='email',
            field=models.TextField(default='null'),
        ),
    ]
