# Generated by Django 4.0.1 on 2022-04-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_articles_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='email',
        ),
    ]
